export default [
  {
    id: "1",
    title: "Sürətli pul krediti",
    price: "2500",
    date: "15.09.2024",
    status: "Təsdiqlənib",
    mounth: "24",
    percent: "24%",
    activeCredit: "true",
    type: "above",
  },
  {
    id: "2",
    title: "Sürətli pul krediti",
    price: "/",
    date: "15.09.2024",
    status: "Təsdiqlənib",
    mounth: "24",
    percent: "20%",
    activeCredit: "true",
    type: "belove",
  },
  {
    id: "3",
    title: "Lombard kreditləri",
    price: "2500",
    date: "15.09.2024",
    status: "Baxılır",
    mounth: "24",
    percent: "20%",
    activeCredit: "false",
    type: "partners",
  },
  {
    id: "4",
    title: "İpoteka kreditləri",
    price: "2500",
    date: "15.09.2024",
    status: "Təsdiqlənib",
    mounth: "24",
    percent: "20%",
    activeCredit: "false",
    type: "partners",
  },
  {
    id: "5",
    title: "Biznes kreditləri",
    price: "2500",
    date: "15.09.2024",
    status: "Baxılır",
    mounth: "24",
    percent: "20%",
    activeCredit: "false",
    type: "partners",
  },
  {
    id: "6",
    title: "Avtokredit",
    price: "2500",
    date: "15.09.2024",
    status: "İmtina olunub",
    mounth: "24",
    percent: "20%",
    activeCredit: "false",
    type: "partners",
  },
];
