pipelines:
  default:
    - parallel:
      - step:
          name: Backend Build and Test
          image: maven:3.8.7
          caches:
            - maven
          script:
            - cd backend/kredit
            - mvn -B verify --file pom.xml
          after-script:              
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Backend Security Scan
          script:            
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Admin v2 Build and Test
          image: node:18
          caches:
            - node
          script:
            - apt-get update
            - apt-get install -y zip
            - npm i -g yarn
            - cd admin_v2
            - yarn install
            - yarn test
            - yarn build
      - step:
            name: Admin v2 Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1      