import {scale} from 'react-native-size-matters';
export const inputWidth = '100%';
export const inputHeight = scale(55);
export const borderRadius = scale(8);
export const fontSize8 = '8@s';
export const fontSize10 = '10@s';
export const fontSize12 = '12@s';
export const fontSize14 = '14@s';
export const fontSize16 = '16@s';
export const fontSize18 = '18@s';
export const fontSize20 = '20@s';
export const fontSize24 = '24@s';
export const fontSize36 = '36@s';
