spring.application.name=kredit
server.port=9899

#mongodb
spring.data.mongodb.database=kredit
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# App Properties
kredit.app.jwtSecret=5660e8609367ee03c4545281dcf54666334006f300984862150d75151aaa0671
kredit.app.jwtExpiration= 86400000
kredit.app.refresh-token-expiration=604800000

# api security
kredit.app.api.key=ce728500-f1c0-43dd-b093-4fc672a0f8ce

#email send properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meherremova.afer2003@gmail.com
spring.mail.password=jfeythzxmioednql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#sms service
smsservice.username=idealkredit_servis
smsservice.password=\u0130dealKredit_2024
smsservice.apiUrl=https://www.poctgoyercini.com/api_json/v1/Sms
smsservice.from=Ideal Kredit

#spring.data.rest
spring.data.rest.basePath=/api
spring.data.rest.detection-strategy=annotated

#logging
logging.level.org.springframework.data=INFO
logging.level.=INFO
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.springframework.controllers=INFO
logging.level.org.springframework.security= INFO
logging.level.az.essam.entezhizmet=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=/tmp/log
logging.file.name=/tmp/log/kredit.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.file.total-size-cap=1GB
spring.main.banner-mode=off

#upload
spring.http.multipart.enabled=true 
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

#storage
storage.location=uploads

#united payment service
united-payment.apiUrl=https://test-vpos.unitedpayment.az/api
united-payment.mail=support@unitedpayment.com
united-payment.password=Testmerchant12!
united-payment.partnerId=b510b3bd8fa04889b0181dfb696ea3e6
united-payment.language=AZ
united-payment.currency=944
united-payment.successUrl=https://ideal-kredit-v2.vercel.app/az/paymentSuccess
united-payment.cancelUrl=https://ideal-kredit-v2.vercel.app/az/paymentCanceled
united-payment.declineUrl=https://ideal-kredit-v2.vercel.app/az/paymentError


# Azinbridge web service
azinbridge.host=https://pre-bridge.rinn.az/api/
azinbridge.key=ESAM-INNOVATIONS-Pre-VgkVzjUMBO2sR5tYtyvzpWN1HcUH0kh5NAp6f6N8NBFmrR0PaUgHr1Y1V9pQLhSvaCq0nGaPSxOeCjfwsTe7ZfOI4a5wDbPaeOKdgefUaBT

# AKB service
# prod: https://app.acb.az/
# dev: https://app.acb.az:8002/
akb.host=https://app.acb.az:8002/
akb.id=IdealKreditBoktWs
akb.password=L7!dPrA>

# asan finance service
# prod url
##asanfinance.apiUrl=http://prod.asanfinance.gov.az
asanfinance.apiUrl=http://test.asanfinance.gov.az:8080
asanfinance.apiKey=K30leUEGYqpqybwufPc45hPuTdNdcYcUlEbX8k4AgQO1BbqaytO5sTT7LPKsG2LwTnm742DAq1M66saDZmX1UP

# sima sdk
sima.masterKey=25CBBCC1-DF52-4C67-BD4F-63420D190B0E
sima.clientId=2144001
sima.baseUrl=https://scanme.sima.az/
sima.clientName=Ideal Kredit
sima.iconUri=https://ideal-kredit-copy.vercel.app/HeaderLogo.png
sima.callBackUri=http://localhost:9899/api/sima/callBack
sima.redirectUri=http://localhost:8080/simalogin
sima.getFileUri=http://localhost:9899/ao\u015f/sima/getFile?tsquery=
sima.getDataUri=http://localhost:9899/api/sima/getData

#e-point pos service
e-point.apiURL=https://epoint.az/api/1/
e-point.privateKey=NJ1LHtZh8hRSlejo6uAeru6p
e-point.publicKey=i000200410
e-point.language=az
e-point.currency=AZN
e-point.successURL=https://app.studentall.az/successPayment.html
e-point.errorUrl=https://app.studentall.az/errorPayment.html
e-point.apiUrl=https://epoint.az/api/1
e-point.origin=https://api.studentall.az:9843