spring.application.name=kredit
server.port=9899

#mongodb
spring.data.mongodb.database=kredit
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# App Properties
kredit.app.jwtSecret=5660e8609367ee03c4545281dcf54666334006f300984862150d75151aaa0671
kredit.app.jwtExpiration= 86400000
kredit.app.refresh-token-expiration=604800000

# api security
kredit.app.api.key=ce728500-f1c0-43dd-b093-4fc672a0f8ce

#email send properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meherremova.afer2003@gmail.com
spring.mail.password=jfeythzxmioednql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#sms service
smsservice.login=username
smsservice.password=password
smsservice.senderName=\u0130deal Kredit
smsservice.apiUrl=https://apps.lsim.az/quicksms/v1
smsservice.from=\u0130deal Kredit

#spring.data.rest
spring.data.rest.basePath=/api
spring.data.rest.detection-strategy=annotated

#logging
logging.level.org.springframework.data=INFO
logging.level.=INFO
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.springframework.controllers=INFO
logging.level.org.springframework.security= INFO
logging.level.az.essam.entezhizmet=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=/tmp/log
logging.file.name=/tmp/log/kredit.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.file.total-size-cap=1GB
spring.main.banner-mode=off

#upload
spring.http.multipart.enabled=true 
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

#storage
storage.location=uploads

#united payment service
united-payment.apiUrl=https://test-vpos.unitedpayment.az/api
united-payment.mail=support@unitedpayment.com
united-payment.password=Testmerchant12!
united-payment.partnerId=b510b3bd8fa04889b0181dfb696ea3e6
united-payment.language=AZ
united-payment.currency=944
united-payment.successUrl=https://ideal-kredit-v2.vercel.app/az/paymentSuccess
united-payment.cancelUrl=https://ideal-kredit-v2.vercel.app/az/paymentCanceled
united-payment.declineUrl=https://ideal-kredit-v2.vercel.app/az/paymentError