export const ayliqdataset = [
  {
    london: 59,
    paris: 57,
    newYork: 86,
    seoul: 21,
    month: 'Yanvar',
  },
  {
    london: 50,
    paris: 52,
    newYork: 78,
    seoul: 28,
    month: 'Fevral',
  },
  {
    london: 47,
    paris: 53,
    newYork: 106,
    seoul: 41,
    month: 'Mart',
  },
  {
    london: 54,
    paris: 56,
    newYork: 92,
    seoul: 73,
    month: 'Aprel',
  },
  {
    london: 57,
    paris: 69,
    newYork: 92,
    seoul: 99,
    month: 'May',
  },
  {
    london: 60,
    paris: 63,
    newYork: 103,
    seoul: 144,
    month: 'İyun',
  },
  {
    london: 59,
    paris: 60,
    newYork: 105,
    seoul: 319,
    month: 'İyul',
  },
  {
    london: 65,
    paris: 60,
    newYork: 106,
    seoul: 249,
    month: 'Avgust',
  },
  {
    london: 51,
    paris: 51,
    newYork: 95,
    seoul: 131,
    month: 'Sentyabr',
  },
  {
    london: 60,
    paris: 65,
    newYork: 97,
    seoul: 55,
    month: 'Oktyabr',
  },
  {
    london: 67,
    paris: 64,
    newYork: 76,
    seoul: 48,
    month: 'Noyabr',
  },
  {
    london: 61,
    paris: 70,
    newYork: 103,
    seoul: 25,
    month: 'Dekab',
  },
];

export const heftelikdataset = [
  {
    london: 50,
    paris: 52,
    newYork: 78,
    seoul: 28,
    month: '1-ci həftə',
  },
  {
    london: 47,
    paris: 53,
    newYork: 106,
    seoul: 41,
    month: '2-ci həftə',
  },
  {
    london: 54,
    paris: 56,
    newYork: 92,
    seoul: 73,
    month: '3-ci həftə',
  },
  {
    london: 57,
    paris: 69,
    newYork: 92,
    seoul: 99,
    month: '4-ci həftə',
  },
];
export const illikdataset = [
  {
    london: 50,
    paris: 52,
    newYork: 78,
    seoul: 28,
    month: '2022',
  },
  {
    london: 47,
    paris: 53,
    newYork: 106,
    seoul: 41,
    month: '2023',
  },
  {
    london: 54,
    paris: 56,
    newYork: 92,
    seoul: 73,
    month: '2024',
  },
  {
    london: 57,
    paris: 69,
    newYork: 92,
    seoul: 0,
    month: '2025',
  },
];
export const gunlukdataset = [
    {
      london: 59,
      paris: 57,
      newYork: 86,
      seoul: 21,
      month: '1',
    },
    {
      london: 50,
      paris: 52,
      newYork: 78,
      seoul: 28,
      month: '2',
    },
    {
      london: 47,
      paris: 53,
      newYork: 106,
      seoul: 41,
      month: '3',
    },
    {
      london: 54,
      paris: 56,
      newYork: 92,
      seoul: 73,
      month: '4',
    },
    {
      london: 57,
      paris: 69,
      newYork: 92,
      seoul: 99,
      month: '5',
    },
    {
      london: 60,
      paris: 63,
      newYork: 103,
      seoul: 144,
      month: '6',
    },
    {
      london: 59,
      paris: 60,
      newYork: 105,
      seoul: 19,
      month: '7',
    },
    {
      london: 65,
      paris: 60,
      newYork: 106,
      seoul: 249,
      month: '8',
    },
    {
      london: 51,
      paris: 51,
      newYork: 95,
      seoul: 131,
      month: '9',
    },
    {
      london: 60,
      paris: 65,
      newYork: 97,
      seoul: 55,
      month: '10',
    },
    {
      london: 67,
      paris: 64,
      newYork: 76,
      seoul: 48,
      month: '11',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '13',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '14',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '15',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '16',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '17',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '18',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '19',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '20',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '21',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '22',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '23',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '24',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '25',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 25,
      month: '26',
    },
    {
      london: 61,
      paris: 70,
      newYork: 1,
      seoul: 32,
      month: '27',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 43,
      month: '28',
    },
    {
      london: 61,
      paris: 70,
      newYork: 43,
      seoul: 12,
      month: '29',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 54,
      month: '30',
    },
    {
      london: 61,
      paris: 70,
      newYork: 103,
      seoul: 54,
      month: '31',
    },
  ];

export function valueFormatter(value: number | null) {
  return `${value} zəng`;
}
